# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  annotatations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: wp.cloudops-1.ucll.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
tls:
- secretname: kuma-tls
- hosts:
  - wp.cloudops-1.ucll.cloud
  

